### ISSUE TITLE
Remove old unused files

### ISSUE THREAD

**Issue by DanielSank** [DanielSank/cappy#11]
In `python/`, `network.py`, `protocol.py`, `calculator.py`, and `client.py` are obsolete. They should probably be removed. However, `network.py` is 50% of a home-spun version of asyncio, so it might be worth keeping it around in case we ever want to finish it for learning purposes.

**Comment by lovesegfault** [comment]
I think it's safe to remove `protocol.py`, `calculator.py`, and `client.py`, they've all been implemented successfully into the new `test.py`, so I don't see why keeping them around.

Regarding `network.py` it'll be stored in the git history if we need it, we shouldn't have to keep it around I guess.

**Comment by DanielSank** [comment]
Changed my mind. Kill the unused files.
