### ISSUE TITLE
PEP-8 and PEP-257 compliance

### ISSUE THREAD

**Issue by lovesegfault** [DanielSank/cappy#6]
I'll be reviewing the code for PEP-8 compliance.
Do we want to have everything PEP-257 compliant as well? I find it a bliss when you're not familiar with the project, although it can be a little work intensive to implement throughout the code.

**Comment by DanielSank** [comment]
> Do we want to have everything PEP-257 compliant as well?

I normally use [Google style docstrings](https://google.github.io/styleguide/pyguide.html) but I'm open to using the community standard. I agree that especially with dynamic languages it's important to have good docs.

**Comment by lovesegfault** [comment]
I'd prefer to use the general community standard, even though I don't mind too much and am fine with either. I just thought that since we'll be dealing with data in a couple of different environments having a _docstringful_ code would help anyone trying to comprehend it afterwards.

**Comment by DanielSank** [comment]
> I'd prefer to use the general community standard

Ok sounds good. I reviewed that pull request, by the way.

**Comment by lovesegfault** [comment]
Merged.

**Comment by DanielSank** [comment]
If you put a line in your commit message that says `Fixes #XXX` then issue XXX will automatically close :)

**Comment by lovesegfault** [comment]
Cool, didn't know that!
